export enum AccessLevel {
  View = "View",
  Update = "Update",
  Delete = "Delete",
  CreateCategory = "CreateCategory",
  UpdateCategory = "UpdateCategory",
  DeleteCategory = "DeleteCategory",
  AddUser = "AddUser",
  UpdateUser = "UpdateUser",
  DeleteUser = "DeleteUser",
  CreateTag = "CreateTag",
  UpdateTag = "UpdateTag",
  DeleteTag = "DeleteTag",
  CreateExpense = "CreateExpense",
  UpdateExpense = "UpdateExpense",
  DeleteExpense = "DeleteExpense",
}
