export enum ErrorType {
  TokenNotProvided = "TokenNotProvided",
  TokenIsInvalid = "TokenIsInvalid",
  AuthorizationFailed = "AuthorizationFailed",
  AccessDenied = "AccessDenied",
  AccessCheckFailed = "AccessCheckFailed",

  UserIdNotProvided = "UserIdNotProvided",
  UserNotFound = "UserNotFound",
  UserFetchError = "UserFetchError",
  UserNotInWallet = "UserNotInWallet",
  WalletUserDeletionError = "WalletUserDeletionError",
  WalletLeaveError = "WalletLeaveError",

  WalletIdNotProvided = "WalletIdNotProvided",
  UserOrWalletIdNotProvided = "UserOrWalletIdNotProvided",
  WalletNameNotProvided = "WalletNameNotProvided",
  CreatorIdNotProvided = "CreatorIdNotProvided",
  WalletIdIsInvalid = "WalletIdIsInvalid",
  WalletDataNotProvided = "WalletDataNotProvided",
  WalletNameIsInvalid = "WalletNameIsInvalid",
  WalletFetchError = "WalletFetchError",
  WalletExists = "WalletExists",
  WalletCreationError = "WalletCreationError",
  WalletNotFound = "WalletNotFound",
  WalletDeletionError = "WalletDeletionError",
  WalletCreatorIsImmutable = "WalletCreatorIsImmutable",

  InvitationNotFound = "InvitationNotFound",
  InvitationExpired = "InvitationExpired",
  InvitationRunOut = "InvitationRunOut",
  InvitationCreationError = "InvitationCreationError",
  InvitationTokenNotProvided = "InvitationTokenNotProvided",

  CategoryCreationError = "CategoryCreationError",
  CategoryExists = "CategoryExists",
  ParentCategoryNotFound = "ParentCategoryNotFound",
  CategoryNotFound = "CategoryNotFound",
  CategoryEditError = "CategoryEditError",
  CategoryDeleteError = "CategoryDeleteError",
  CategoryHasExpenses = "CategoryHasExpenses",
  ParentCategoryHasExpenses = "ParentCategoryHasExpenses",
  SourceCategoryNotFound = "SourceCategoryNotFound",
  TargetCategoryNotFound = "TargetCategoryNotFound",

  TagCreationError = "TagCreationError",
  TagExists = "TagExists",
  TagNotFound = "TagNotFound",
  TagUpdateError = "TagUpdateError",
  TagDeleteError = "TagDeleteError",

  ExpenseCreationError = "ExpenseCreationError",
  ExpenseNotFound = "ExpenseNotFound",
  ExpenseUpdateError = "ExpenseUpdateError",
  ExpenseDeletionError = "ExpenseDeletionError",
  ExpenseFetchError = "ExpenseFetchError",
  ExpenseTransferError = "ExpenseTransferError",
  ExpensesNotFound = "ExpensesNotFound",
}
