export enum ErrorType {
  UserIdNotProvided = "UserIdNotProvided",
  WalletIdNotProvided = "WalletIdNotProvided",
  NoTokenProvided = "NoTokenProvided",
  AuthorizationFailed = "AuthorizationFailed",
  NoWalletData = "NoWalletData",
  WalletFetchError = "WalletFetchError",
  WalletExists = "WalletExists",
  WalletCreationError = "WalletCreationError",
  WalletNotFound = "WalletNotFound",
  WalletDeletionError = "WalletDeletionError",
  InvitationNotFound = "InvitationNotFound",
  InvitationExpired = "InvitationExpired",
  InvitationRunOut = "InvitationRunOut",
  UserFetchError = "UserFetchError",
  InvitationCreationError = "InvitationCreationError",
  InvitationTokenNotProvided = "InvitationTokenNotProvided",
  UserNotFound = "UserNotFound",
}
